name: test
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up emsdk
        uses: mymindstorm/setup-emsdk@v11
        with:
          version: 3.1.10
          actions-cache-folder: "emsdk-cache"

      - name: Verify emsdk
        run: emcc --check

      - name: yarn cache
        uses: c-hive/gha-yarn-cache@v2

      - run: yarn install

      - name: Build
        run: ./build.sh

      - run: yarn test
